name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm32-wasi
      run: rustup target add wasm32-wasi
    - name: Build
      run: cargo build --target=wasm32-wasi --verbose
    - name: Run tests
      run: cargo build --target=wasm32-wasi --verbose
